### ISSUE TITLE
Cannot change whether this adapter has stable IDs while the adapter has registered observers.

### ISSUE THREAD

**Issue by ParagBhuse12** [mohlendo/ReorderRecyclerView#3]
Getting a crash while implementation. 

Cannot change whether this adapter has stable IDs while the adapter has registered observers.
LogCat- 

at android.support.v7.widget.RecyclerView$Adapter.setHasStableIds(RecyclerView.java:6135)
at android.support.v4.app.Fragment.performCreateView(Fragment.java:2087)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1113)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
                                                                            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                                                                            at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1643)
                                                                            at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:679)
                                                                            at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:166)
                                                                            at android.support.v4.view.ViewPager.populate(ViewPager.java:1272)
                                                                            at android.support.v4.view.ViewPager.populate(ViewPager.java:1120)
                                                                            at android.support.v4.view.ViewPager$3.run(ViewPager.java:277)
                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:696)
                                                                            at android.view.Choreographer.doFrame(Choreographer.java:628)
                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
                                                                            at android.os.Handler.handleCallback(Handler.java:822)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                            at android.os.Looper.loop(Looper.java:207)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5774)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:681)

If you can please help me in this.

**Comment by kuffs** [comment]
I think this library is abandoned.

Check out https://github.com/h6ah4i/android-advancedrecyclerview instead.
